# Generated by Django 5.2.1 on 2025-05-09 01:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('Pasaporte', 'Pasaporte'), ('Carnet de extranjería', 'Carnet de extranjería')], default='DNI', verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono/Celular')),
                ('domicilio', models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('tipo_producto_servicio', models.CharField(choices=[('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio')], default='PRODUCTO', max_length=20, verbose_name='Producto / Servicio')),
                ('descripcion_producto_servicio', models.CharField(max_length=255, verbose_name='Descripción del Producto / Servicio')),
                ('monto_reclamo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto del bien objeto de Reclamo')),
                ('numero_pedido', models.CharField(blank=True, default='', max_length=50, verbose_name='Número de Pedido (Opcional)')),
                ('tipo_reclamacion', models.CharField(choices=[('RECLAMO', 'Reclamo'), ('QUEJA', 'Queja')], default='RECLAMO', max_length=20, verbose_name='Tipo de reclamación')),
                ('detalle_reclamo', models.TextField(verbose_name='Detalle del Reclamo')),
                ('mensaje', models.TextField(blank=True, default='', verbose_name='Mensaje adicional')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Reclamación',
                'verbose_name_plural': 'Reclamaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
